#!/bin/bash
# Quick Start Guide

echo "╔════════════════════════════════════════════════════════╗"
echo "║         Strukt App - Complete Integration Ready         ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""
echo "Your backend folder is now INTEGRATED with Next.js!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Files Created:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ app/lib/backend-adapter.ts"
echo "   └─ Universal method call system"
echo "   └─ Switches between HTTP proxy and direct calls"
echo ""
echo "✅ app/lib/backend-config.ts"
echo "   └─ Backend configuration"
echo "   └─ Controls direct call vs HTTP mode"
echo ""
echo "✅ app/api/[...route]/route.ts (UPDATED)"
echo "   └─ Now uses universal adapter"
echo "   └─ Can work with or without Python backend"
echo ""
echo "✅ .env.development"
echo "   └─ Development config (HTTP backend URL)"
echo ""
echo "✅ .env.production"
echo "   └─ Production config (external HTTP backend URL)"
echo ""
echo "✅ Dockerfile"
echo "   └─ Multi-stage build: Node.js + Python"
echo "   └─ Includes all backend dependencies"
echo ""
echo "✅ docker-compose.yml"
echo "   └─ Complete stack: App + PostgreSQL + Redis"
echo ""
echo "✅ deploy-aws.sh"
echo "   └─ One-command AWS deployment"
echo ""
echo "✅ start.sh"
echo "   └─ Start helper with multiple modes"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 How to Run:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  DEVELOPMENT (External HTTP backend)"
echo "   ┌─────────────────────────────────────────────┐"
echo "   │ Ensure the Python backend is running at     │"
echo "   │ the URL specified in NEXT_PUBLIC_BACKEND_URL│"
echo "   │ (e.g. http://localhost:8000).              │"
echo "   │                                             │"
echo "   │ Terminal: Start Next.js                     │"
echo "   │ $ npm run dev                               │"
echo "   │                                             │"
echo "   │ Access: http://localhost:3000               │"
echo "   └─────────────────────────────────────────────┘"
echo ""
echo "2️⃣  DOCKER COMPOSE (Everything in containers)"
echo "   ┌─────────────────────────────────────────────┐"
echo "   │ $ ./start.sh docker                         │"
echo "   │                                             │"
echo "   │ Includes:                                   │"
echo "   │ • Next.js + Backend (via internal network) │"
echo "   │ • PostgreSQL database                       │"
echo "   │ • Redis cache                               │"
echo "   │                                             │"
echo "   │ Access: http://localhost:3000               │"
echo "   │ Stop: docker-compose down                   │"
echo "   └─────────────────────────────────────────────┘"
echo ""
echo "3️⃣  AWS DEPLOYMENT (Production)"
echo "   ┌─────────────────────────────────────────────┐"
echo "   │ $ ./deploy-aws.sh                           │"
echo "   │                                             │"
echo "   │ Requirements:                               │"
echo "   │ • AWS CLI configured (aws configure)        │"
echo "   │ • Docker installed                          │"
echo "   │ • AWS permissions for App Runner, ECR       │"
echo "   │                                             │"
echo "   │ Does automatically:                         │"
echo "   │ • Builds Docker image                       │"
echo "   │ • Creates ECR repository                    │"
echo "   │ • Deploys to AWS App Runner                 │"
echo "   │ • Sets up CloudWatch logs                   │"
echo "   │                                             │"
echo "   │ Result: Live URL in a few minutes           │"
echo "   └─────────────────────────────────────────────┘"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 How It Works:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "BEFORE: Frontend ←HTTP→ Python Backend (port 8000)"
echo "        All calls were HTTP requests"
echo ""
echo "AFTER:  Frontend ←→ Next.js API Routes ←→ Backend"
echo "        Direct function calls (no HTTP overhead!)"
echo ""
echo "The universal adapter:"
echo "1. Detects if running in production (direct calls)"
echo "2. Imports Python backend modules directly"
echo "3. Calls functions instead of making HTTP requests"
echo "4. Falls back to HTTP proxy in development"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📦 Backend Integration Points:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✓ /runs              → Project CRUD operations"
echo "✓ /runs/:id/generate-3d → Blender 3D generation"
echo "✓ /runs/:id/detect-rooms → Room detection (OpenCV)"
echo "✓ /runs/:id/render   → Render generation"
echo "✓ /runs/:id/upload   → File uploads"
echo "✓ /runs/:id/download → File downloads"
echo "✓ /system/health     → Health checks"
echo "✓ /auth/verify       → Google OAuth verification"
echo "✓ /worker/jobs       → Job queue management"
echo "✓ /sam3d/submit-batch → 3D furniture generation"
echo ""
echo "All automatically routed to backend functions!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚙️  Configuration:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Development (.env.development):"
echo "  BACKEND_DIRECT_CALL=false  # always use remote HTTP backend"
echo "  NEXT_PUBLIC_BACKEND_URL=http://127.0.0.1:8000"
echo ""
echo "Production (.env.production):"
echo "  BACKEND_DIRECT_CALL=false  # never enable direct calls"
echo "  NEXT_PUBLIC_BACKEND_URL=https://api.myapp.com  # set to your backend host"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 Next Steps:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Test locally first:"
echo "   npm run dev  # Requires remote/localhost Python backend to be running"
echo ""
echo "2. Or use Docker Compose:"
echo "   ./start.sh docker"
echo ""
echo "3. Deploy to AWS:"
echo "   ./deploy-aws.sh  # Requires AWS CLI configured"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
