receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}

exporters:
  otlp:
    endpoint: "http://signoz:4317"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      exporters: [otlp]
